name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
#    - name: Install Conan to fetch package dependencies
#      id: conan
#      uses: turtlebrowser/get-conan@main

#    - name: Conan version
#      run: echo "${{ steps.conan.outputs.version }}"

#    - name: Create default Conan profile
#      run: conan profile detect --force

    - name: Run build script
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        CMD_RES=`ls -la ${{ github.workspace }}`
        echo ${CMD_RES}
        ./run_build.sh

    - name: Run test
      shell: bash
      run: |
       cd ${{ github.workspace }}/build-x64
       make test




