name: Windows MSVC build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Build_and_run_tests:
    runs-on: windows-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4    

    - name: Install Conan to fetch package dependencies
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Create default Conan profile
      run: conan profile detect --force

    - name: Configure CMake
      shell: pwsh
      run: |
       $env:CC = "gcc"
       $env:CXX = "g++"
       cmake -S . -B build-x64 -G "Visual Studio 17 2022" -D CMAKE_BUILD_TYPE=Release


    - name: Build
      shell: pwsh
      run: |
        # Similar to running: $GITHUB_WORKSPACE/run_build.cmd
        cmake --build .\build-x64 --config Release

    - name: Run tests
      shell: pwsh
      run: |
       cd $env:GITHUB_WORKSPACE\build-x64
       ctest -C Release

