name: Windows MSVC build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Build_and_run_tests:
    runs-on: windows-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Cache Conan Dependencies
      # Caches required packages, e.g. gtest
      if: false  # Disables this step. It creates cache on storage too quickly.
      uses: actions/cache@v4.2.3
      with:
        path: C:\Users\runneradmin\.conan2\p
        key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}
        restore-keys: |
          conan-${{ runner.os }}-

    - name: Install Conan to fetch package dependencies
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Create default Conan profile
      run: conan profile detect --force

    - name: Conan install
      run: conan install . -s build_type=Release -s compiler.cppstd=23 --output-folder=build-x64\conan --build=missing

    - name: Configure CMake
      shell: pwsh
      run: |
       cd $env:GITHUB_WORKSPACE\build-x64
       cmake -S .. -B . -G "Visual Studio 17 2022" -D CMAKE_TOOLCHAIN_FILE=.\conan\conan_toolchain.cmake -D CMAKE_BUILD_TYPE=Release

    - name: Build
      shell: pwsh
      run: |
        # Similar to running: $GITHUB_WORKSPACE/run_build.cmd
        cmake --build .\build-x64 --config Release

    - name: Run tests
      shell: pwsh
      run: |
       cd $env:GITHUB_WORKSPACE\build-x64
       ctest -C Release

