name: Windows Clang build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Verify Clang
        run: clang++ --version

      - name: Configure Xmake
        run: xmake f -y

      - name: Build
        run: xmake -y

      - name: Run tests
        run: xmake test -y
